# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bsbssh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_4482d89382c74ddb9610ee53594df1fc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_449c4bf56e0e4028b262f0684a6e720c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_4482d89382c74ddb9610ee53594df1fc }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bsbssh'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c113c363d495431daa5cd263bbe87e9b }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_4482d89382c74ddb9610ee53594df1fc }}/appsvc/staticsite:${{ github.sha }}'